CREATE TABLE IF NOT EXISTS Person (
                                      person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      person_fio varchar (100) NOT NULL UNIQUE,
                                      person_year_born int check ( person_year_born > 1900 ) NOT NULL
);

insert into person (person_fio, person_year_born) VALUES ('Иванов Иван Иванович', 1978);
insert into person (person_fio, person_year_born) VALUES ('Петров Леонид Федорович', 1986);
insert into person (person_fio, person_year_born) VALUES ('Сидоров Валентин Леонидович', 1986);

CREATE TABLE IF NOT EXISTS Book (
                                    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    person_id int REFERENCES Person(person_id) ON DELETE SET NULL,
                                    book_name varchar (100) NOT NULL,
                                    book_author varchar (100) NOT NULL,
                                    book_year int check ( book_year > 0 ) NOT NULL
);

insert into book (book_name, book_author, book_year) values ('Монах который продал свой феррари', 'Робин Шарма', 2022);
insert into book (book_name, book_author, book_year) values ('Соленая тропа', 'Рэйнор Винн', 2022);
insert into book (book_name, book_author, book_year) values ('Кто заплачет, когда ты умрешь?', 'Робин Шарма', 2022);